[package]
name = "oanda-rs"
version = "0.1.0"
authors = ["Zach Blankenship <zach.blankenship@gmail.com>"]

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
