[package]
name = "oanda-rs"
version = "0.1.0"
authors = ["Zach Blankenship <zach.blankenship@gmail.com>"]

[dependencies]
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
