version: '3.0'

services:
  lib: &default
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry
    env_file: .secrets

volumes:
  registry:
    driver: local
